# Generated by Django 6.0.3 on 2026-03-13 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='useraccount',
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
