# Generated by Django 6.0.3 on 2026-03-13 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_student_useraccount_attendance_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtimetable',
            name='subject',
        ),
        migrations.AddField(
            model_name='examtimetable',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='examtimetable',
            name='timing',
            field=models.CharField(max_length=50),
        ),
    ]
