# Generated by Django 6.0.3 on 2026-03-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_examtimetable_subject_examtimetable_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherclassschedule',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
