# Generated by Django 6.0.3 on 2026-03-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_teacherclassschedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
