# Generated by Django 6.0.3 on 2026-03-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_fee_pending_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.course'),
            preserve_default=False,
        ),
    ]
