# Generated by Django 6.0.3 on 2026-03-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_result_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='otp_verified',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
