# Generated by Django 6.0.3 on 2026-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_result_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
